# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY studentadmissionsvc.balx /home/ballerina 

EXPOSE  9102
CMD ballerina run  studentadmissionsvc.balx
