# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY staffrecruitmentssvc.balx /home/ballerina 

EXPOSE  9095
CMD ballerina run  staffrecruitmentssvc.balx
