# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY registerstudentssvc.balx /home/ballerina 

EXPOSE  9092
CMD ballerina run  registerstudentssvc.balx
