# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY coursecataloguesvc.balx /home/ballerina 

EXPOSE  9093
CMD ballerina run  coursecataloguesvc.balx
