CREATE DATABASE IF NOT EXISTS credit_db;

USE credit_db;

CREATE TABLE  IF NOT EXISTS `CUSTOMER_CREDIT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` VARCHAR(45) DEFAULT NULL,
  `REFERENCE_NUMBER` VARCHAR(45) DEFAULT NULL,
  `AMOUNT` DECIMAL(20,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=82781213 DEFAULT CHARSET=latin1;