version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5

  is:
    image: docker.wso2.com/wso2is:5.5.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 15
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./is:/home/wso2carbon/wso2-volume
    ports:
      - "9763:9763"
      - "9443:9443"
    links:
      - mysql

  api-manager:
    image: docker.wso2.com/wso2am:2.2.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9444/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
      is:
        condition: service_healthy
    volumes:
      - ./apim:/home/wso2carbon/volumes
    ports:
      - "9764:9764"
      - "9444:9444"
      - "8281:8281"
      - "8244:8244"
    links:
      - mysql
      - is
