# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY paymentrecordsvc.balx /home/ballerina 

EXPOSE  9094
CMD ballerina run  paymentrecordsvc.balx
